<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IND062" name="API.com.project.api.TestClass" tests="4" failures="1" timestamp="16 Aug 2017 10:37:53 GMT" time="10.804" errors="0">
  <testcase name="test_OffSet_And_Max_When_Set_To_Same_Value_Recors_Are_Duisplayed_With_Same_Value" time="3.202" classname="API.com.project.api.TestClass">
    <failure type="java.lang.AssertionError" message="No of records didn&#039;t macth when usong pagesize expected [12] but found [8]">
      <![CDATA[java.lang.AssertionError: No of records didn't macth when usong pagesize expected [12] but found [8]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at RestAssureHelper.RestAssuredHelper.checkArraySizeInResponse(RestAssuredHelper.java:95)
	at API.com.project.api.TestClass.test_OffSet_And_Max_When_Set_To_Same_Value_Recors_Are_Duisplayed_With_Same_Value(TestClass.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_OffSet_And_Max_When_Set_To_Same_Value_Recors_Are_Duisplayed_With_Same_Value -->
  <testcase name="T2_test_All_Headers_Are_Present_In_The_Response" time="0.003" classname="API.com.project.api.TestClass"/>
  <testcase name="T1_test_Http_Status_Code_For_The_Courses_API" time="7.597" classname="API.com.project.api.TestClass"/>
  <testcase name="T3_test_More_Than_Records_Are_Returned_From_The_Call" time="0.002" classname="API.com.project.api.TestClass"/>
</testsuite> <!-- API.com.project.api.TestClass -->
